name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Doxygen
        run: |
          sudo apt-get install -y doxygen
          doxygen Doxyfile
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
